### ISSUE TITLE
Problem with not returning scobra objects 

### ISSUE THREAD

**Issue by mauriceccy** [mauriceccy/scobra#12]
fva.AsMtx() doesn't give a matrix object
model.GetSol() doesn't give a flux object (only an empty dictionary) when there is no solution

**Comment by kristoforusbryant** [comment]
Bug fixed in commit acb4cdb23ab5a3ec54482f69dd6f57dc7eb02087.

**Comment by mauriceccy** [comment]
similarly for flux.Diff

**Comment by dombong** [comment]
Should be fixed for python3 now with update 1.11 commit
