### ISSUE TITLE
ConstraintScan putting cobra=True option

### ISSUE THREAD

**Issue by mauriceccy** [mauriceccy/scobra#15]
currently the ConstraintScan has MinFlux=True option which uses MinFluxSolve. It would be good to add allow to user to choose MinFluxSolve(cobra=True). Currently the default is False and there is no option to make it True.

Would be good to implement both:
i) Add an option to allow user to choose cobra=True when MinFlux=True
ii) make cobra=True the default

**Comment by dombong** [comment]
resolved for python3 with update 1.9 commit
