### ISSUE TITLE
MinFluxSolve stopped after infeasible

### ISSUE THREAD

**Issue by mauriceccy** [mauriceccy/scobra#16]
The old version of scobra (available in our Frontiers dfba paper's supplementary) works (Windows 10) but latest (downloaded from github recently in virtualbox Ubuntu linux) not working. This problem happens with MinFluxSolve in the latest scobra but not in the old version. In old version after infeasible, codes continues for next iteration. I will try to update again.

Error:
/usr/local/lib/python2.7/dist-packages/cobra/util/solver.pyc in assert_optimal(model, message)
    423     """
    424     if model.solver.status != optlang.interface.OPTIMAL:
--> 425         raise OPTLANG_TO_EXCEPTIONS_DICT[model.solver.status](message)

Infeasible: None

**Comment by rahulnutron** [comment]
I was using old version.
